# .readthedocs.yaml
# Read the Docs configuration file
# Version: 1.0.0
# Date: 2026-02-16

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - echo "Building STALWART documentation"
      - pip install -e .[docs]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

formats:
  - pdf
  - epub
  - htmlzip

submodules:
  include: all
  recursive: true

search:
  ranking:
    api/*: 5
    installation/*: 3
    user-guide/*: 3
    research/*: 4

redirects:
  index: README.md
  quickstart: installation/quick-start.md
  api: api/overview.md
