#!/usr/bin/env python3
"""Generate a single unified TXT report for all bridges."""

from pathlib import Path
from datetime import datetime

now = datetime.now()
reports_dir = Path("reports/unified")
reports_dir.mkdir(parents=True, exist_ok=True)

# بيانات جميع الجسور
bridges_data = [
    {
        "id": "BR-001",
        "name": "North Bridge",
        "location": "New York, NY",
        "type": "Suspension",
        "age": 45,
        "health": "91%",
        "status": "SAFE",
        "risk": "LOW",
        "afc": "0.32",
        "alsa": "0.45",
        "cpii": "0.94",
        "ffd": "1.2",
        "lts": "12.5",
        "ccf": "28.3",
        "tvr": "0.92",
        "bd": "5.2",
        "sed": "32.1",
        "alerts": "None",
        "reco": "Routine monitoring"
    },
    {
        "id": "BR-002",
        "name": "South Bridge",
        "location": "Los Angeles, CA",
        "type": "Cable-stayed",
        "age": 28,
        "health": "98%",
        "status": "SAFE",
        "risk": "LOW",
        "afc": "0.21",
        "alsa": "0.38",
        "cpii": "0.97",
        "ffd": "0.8",
        "lts": "8.2",
        "ccf": "18.5",
        "tvr": "0.95",
        "bd": "3.8",
        "sed": "25.4",
        "alerts": "None",
        "reco": "Continue routine"
    },
    {
        "id": "BR-003",
        "name": "East Bridge",
        "location": "Chicago, IL",
        "type": "Arch",
        "age": 62,
        "health": "99%",
        "status": "SAFE",
        "risk": "LOW",
        "afc": "0.18",
        "alsa": "0.29",
        "cpii": "0.98",
        "ffd": "0.5",
        "lts": "6.8",
        "ccf": "15.2",
        "tvr": "0.97",
        "bd": "2.9",
        "sed": "22.8",
        "alerts": "None",
        "reco": "Excellent"
    },
    {
        "id": "BR-004",
        "name": "West Bridge",
        "location": "Seattle, WA",
        "type": "Steel girder",
        "age": 38,
        "health": "96%",
        "status": "WARNING",
        "risk": "MEDIUM",
        "afc": "0.28",
        "alsa": "0.52",
        "cpii": "0.92",
        "ffd": "1.8",
        "lts": "15.3",
        "ccf": "32.7",
        "tvr": "0.89",
        "bd": "6.5",
        "sed": "38.9",
        "alerts": "⚠️ ALSA increasing",
        "reco": "Monitor strain gauge"
    },
    {
        "id": "TEST-001",
        "name": "Test Bridge",
        "location": "Research Facility",
        "type": "Suspension",
        "age": 25,
        "health": "94.7%",
        "status": "SAFE",
        "risk": "LOW",
        "afc": "0.42",
        "alsa": "0.58",
        "cpii": "0.91",
        "ffd": "2.3",
        "lts": "18.5",
        "ccf": "34.2",
        "tvr": "0.88",
        "bd": "8.4",
        "sed": "42.3",
        "alerts": "None",
        "reco": "Check calibration"
    }
]

# قالب التقرير الموحد
UNIFIED_TEMPLATE = """================================================================================
                    STALWART BRIDGE MONITORING SYSTEM
                          UNIFIED DAILY REPORT
================================================================================
Report Date    : {date}
Generated      : {timestamp}
Total Bridges  : {total_bridges}
================================================================================

SUMMARY TABLE
================================================================================
ID       | Name           | Health | Status  | Risk   | Key Alert
---------|----------------|--------|---------|--------|------------------
{table_rows}

================================================================================
DETAILED BRIDGE REPORTS
================================================================================
{detailed_reports}

================================================================================
STATISTICS
================================================================================
Total Bridges Monitored : {total_bridges}
Bridges in SAFE status  : {safe_count}
Bridges in WARNING status: {warning_count}
Bridges in CRITICAL status: {critical_count}

Average Health Score    : {avg_health}

================================================================================
RECOMMENDATIONS SUMMARY
================================================================================
{recommendations}

================================================================================
End of Report
Generated by STALWART v2.0.0 (AI Edition)
Contact: gitdeeper@gmail.com
================================================================================
"""

def generate_table_row(bridge):
    """Generate a single row for the summary table."""
    name_short = bridge['name'][:12].ljust(12)
    return f"{bridge['id']} | {name_short} | {bridge['health']} | {bridge['status']} | {bridge['risk']} | {bridge['alerts'][:15]}"

def generate_detailed_report(bridge):
    """Generate detailed report for a single bridge."""
    return f"""
BRIDGE: {bridge['id']} - {bridge['name']}
--------------------------------------------------------------------------------
Location     : {bridge['location']}
Type         : {bridge['type']}
Age          : {bridge['age']} years
Health       : {bridge['health']}
Status       : {bridge['status']}
Risk Level   : {bridge['risk']}

NINE PARAMETERS:
--------------------------------------------------------------------------------
1. AFC (Aeroelastic Flutter)    : {bridge['afc']}
2. ALSA (Strain Accumulation)   : {bridge['alsa']}
3. CPII (Cable Integrity)       : {bridge['cpii']}
4. FFD (Frequency Drift)        : {bridge['ffd']}%
5. LTS (Thermal Stress)         : {bridge['lts']}%
6. CCF (Corrosion)              : {bridge['ccf']}%
7. TVR (Vibration)              : {bridge['tvr']}
8. BD (Displacement)            : {bridge['bd']} mm
9. SED (Strain Energy)          : {bridge['sed']}%

ALERTS:
--------------------------------------------------------------------------------
{bridge['alerts']}

RECOMMENDATIONS:
--------------------------------------------------------------------------------
{bridge['reco']}
--------------------------------------------------------------------------------
"""

def generate_recommendations_summary(bridges):
    """Generate summary of all recommendations."""
    lines = []
    for b in bridges:
        lines.append(f"• {b['id']}: {b['reco']}")
    return "\n".join(lines)

# Generate the unified report
table_rows = []
detailed_reports = []
safe_count = 0
warning_count = 0
critical_count = 0
health_sum = 0.0

for bridge in bridges_data:
    table_rows.append(generate_table_row(bridge))
    detailed_reports.append(generate_detailed_report(bridge))
    
    if bridge['status'] == "SAFE":
        safe_count += 1
    elif bridge['status'] == "WARNING":
        warning_count += 1
    elif bridge['status'] == "CRITICAL":
        critical_count += 1
    
    # Extract numeric health value for average
    health_val = float(bridge['health'].replace('%', ''))
    health_sum += health_val

avg_health = health_sum / len(bridges_data)

recommendations = generate_recommendations_summary(bridges_data)

# Create the final report
final_report = UNIFIED_TEMPLATE.format(
    date=now.strftime('%Y-%m-%d'),
    timestamp=now.strftime('%Y-%m-%d %H:%M:%S'),
    total_bridges=len(bridges_data),
    table_rows="\n".join(table_rows),
    detailed_reports="".join(detailed_reports),
    safe_count=safe_count,
    warning_count=warning_count,
    critical_count=critical_count,
    avg_health=f"{avg_health:.1f}%",
    recommendations=recommendations
)

# Save the unified report
report_file = reports_dir / f"STW-UNIFIED-{now.strftime('%Y%m%d')}.txt"
with open(report_file, 'w', encoding='utf-8') as f:
    f.write(final_report)

print("=" * 80)
print("📊 STALWART UNIFIED REPORT GENERATOR")
print("=" * 80)
print(f"✅ Unified report created: {report_file}")
print(f"📁 Location: reports/unified/")
print(f"📦 Size: {len(final_report)} characters")
print("=" * 80)

# Display the summary table
print("\n📋 SUMMARY TABLE:")
print("-" * 60)
print("ID       | Name           | Health | Status  | Risk   | Alert")
print("-" * 60)
for row in table_rows:
    print(row)
print("-" * 60)
print(f"\n📊 Statistics: {safe_count} SAFE, {warning_count} WARNING, {critical_count} CRITICAL")
print(f"📈 Average Health: {avg_health:.1f}%")
print("=" * 80)
